name: Build and deploy main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.1.5

      - name: Run cypress tests
        uses: cypress-io/github-action@v5
        with:
         build: npm run build
         start: npm start

      - name: Connect to production server and update production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: ./updateFront.sh > logFrontUpdate.log 2>&1
          
