name: Build and deploy main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      
      - name: Install and build
        run: |
          npm install
          npm run build
          
      - name: Copy dist folder to remote server
        run: |
          scp -r dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}:~/var/www/html/deverr.fr
          echo "dist folder copied to remote server"
          
      - name: Connect to production server and update production
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_IP }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
